#!/usr/bin/with-contenv bash

# Copy config
[[ ! -f /config/mosquitto.conf ]] && cp \
	/defaults/mosquitto.conf /config/mosquitto.conf

# Permissions
chown abc:abc -R \
    /config \
	/data \
    /log
